check test.log exist

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -31,14 +31,19 @@ jobs:
       - name: Check
         shell: bash
         run: | 
-          result=$(grep -Po 'failed' test.log)
-          if [ -z "$result" ]; then 
-              echo "OK"
-              exit 0
-          else
-              echo "FAIL"
-              exit 1
-          fi 
+          if [ -f "test.log" ]; then
+            result=$(grep -Po 'failed' test.log)
+            if [ -z "$result" ]; then 
+                echo "OK"
+                exit 0
+            else
+                echo "FAIL"
+                exit 1
+            fi 
+          else 
+            echo "OK"
+            exit 0
+          fi
   CD:
     needs: [CI]
     if: github.ref == 'refs/heads/main'
