fix if result

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -41,11 +41,11 @@ jobs:
             echo "result inside if: $result"
             echo "ola mundo"
             if [ -z "$result" ]; then 
-                echo "FAIL"
-                exit 1
-            else
                 echo "OK"
                 exit 0
+            else
+                echo "FAIL"
+                exit 1
             fi 
           else 
             echo "arquivo nao existe"
